### ISSUE TITLE
Tap water heating control

### ISSUE THREAD

**Issue by Steven1994** [CJNE/thermiagenesis#22] opened 2022-01-16 14:45 UTC
I've installed the integration in Home assistant and can read out everything of my heating pump (i have a calibra cool 7). 

But the main i want to do is control the upper and lower limit of the tap-water heating system, this to control the usage of solar energy in the summer. 

I've found the following file with every parameter and their adress, the two paramenters I want to control are:
- Start temperature tap water (40023)
- Stop temperature tap water (40024)

https://zupah.be/wp-content/uploads/2021/08/Thermia-Modbus-protocol-for-Genesis-platform-10.pdf

Is there any way I can accomplish this with you plugin?

**Comment by CJNE** [comment] 2022-01-18 14:11
Hello Steven!
Yes this should be possible, when you add this integration you should by default get a climate entity that lets you see the current tap water temperature as well as set the low and hi limits. 
It also has a lot of entities that are disabled by default, you can enable any additional entities in HA config page.

**Comment by Steven1994** [comment] 2022-01-18 15:15
Hi Johan,

Thanks for the very quick reply.

I have indeed seen the options that I can do with the tap water but the heat pump does not react to it. Please see below the screenshots:

Is it possible to check that the addresses you use in your integration are the same then in my heatpump, below you can find them:

  *   Start temperature tap water (40023)
  *   Stop temperature tap water (40024)


***@***.***

***@***.***

Thanks a lot,

Best regards,

Steven

**Comment by CJNE** [comment] 2022-01-18 15:26
Yes I can confirm that it's the same holding registers (22 & 23). There might be a slight delay before it updates the heat pump. 
Also can you have a look in the HA log after you have tried to change the temperature, look for "Set temperature" and then there should be "Write (reg) value (value)", can you confirm this is happening?

**Comment by Steven1994** [comment] 2022-01-18 15:37
Do you mean the log over here?
![image](https://user-images.githubusercontent.com/6698973/149968156-70810ae9-fda1-4550-bf02-4990ff902b8d.png)
There is nothing happening when I change. 

But when I change the set temperature, the graph updates, so I think it goes throug:
![image](https://user-images.githubusercontent.com/6698973/149968470-a4607394-7654-4f50-abe6-8613605e8aed.png)

**Comment by Steven1994** [comment] 2022-01-18 15:40
But it is staying on "Auto" could that be the problem?

![image](https://user-images.githubusercontent.com/6698973/149969043-1040d05f-9411-43c0-87ee-28d21cce5e68.png)

**Comment by Steven1994** [comment] 2022-01-18 17:09
Ok, nevermind, I see the number updating on my heatpump, it is just the fact that is does not start heating when it reaches the temperature. I think this is a protection and that these values cannot be updated during operation. 

The only solution that the installer mentioned was using the smart-grid modes. This is the comfort and the boost mode. Is there any way I can trigger one of those withoud physically hooking up a device to the smart grid ports?

I can read out the ports using the following adresses, but i want to switch the heatpump using the network:
- Smart grid 1: 10202
- Smart grid 2: 10205

![IMG_20220118_180316](https://user-images.githubusercontent.com/6698973/149984924-0f9eca1c-6760-4770-95ea-4261ecaaf5ba.jpg)

**Comment by CJNE** [comment] 2022-01-19 08:02
It should be possible to change these parameters during operation, just like you can do through the touch screen.
I'm not by any means an expert on heat pumps but there can be other things that prevents or delays the heating. 
Doing some tests on my heat pump now to see if this works for me, will get back.
I don't think anything can be done with the smart grid options. 
An option to that is to toggle enable or disable tap water heating completely, this is something I know works.
This is the "Auto" select box, if you turn it off it will disable tap water heating, set it to "Auto" to enable it again.

**Comment by CJNE** [comment] 2022-01-19 08:54
Hmm I'm looking at the graph and came one theory springs to mind. Perhaps the tap water heating only triggers when the temperature reach the low setting, and if you increase that level past the current temperature it will not trigger?
If this is what is happening (which imho is a bug) then perhaps it can be fixed by temporarily disable tap water heating and then enable it again after the temperature has been changed.

**Comment by Steven1994** [comment] 2022-01-19 11:19
Hi, Thanks a lot for the quick replies. 

It is working now, the problem was that the heating pump was set on "eco" and not on the "normal" mode. So everything is working now. It is awesome. 

Thanks a lot for the plugin. 

Best regards,

Steven

**Comment by CJNE** [comment] 2022-01-19 12:24
You're welcome :) 
Good to hear that everything is working!

**Closed by CJNE** 2022-01-19 12:24 UTC
